endpoints:
  enabled: false
  # enable /health endpoint
  health:
    enabled: true
management:
  health:
    defaults:
      enabled: false
httpClient:
  socketTimeout: 1000
  connectionTimeout: 1000